# Generated by Django 4.2.6 on 2023-12-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0002_remove_transformdevice_id_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransformator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_customUser', models.JSONField()),
                ('id_transform', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Дополнительное оборудование Пользователя',
                'verbose_name_plural': 'Дополнительное оборудование Пользователя',
            },
        ),
        migrations.CreateModel(
            name='TransformDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Trans', models.CharField(max_length=50)),
                ('TransPrimary', models.IntegerField()),
                ('TransSecondary', models.IntegerField()),
                ('TransType', models.CharField(max_length=100)),
                ('TransPrecision', models.FloatField()),
                ('TransInterval', models.IntegerField()),
                ('id_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtoriz.deviceaccount')),
            ],
            options={
                'verbose_name': 'Трансформатор',
                'verbose_name_plural': 'Трансформатор',
            },
        ),
    ]
