# Generated by Django 4.2.6 on 2023-12-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0003_usertransformator_transformdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformdevice',
            name='Trans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transformdevice',
            name='TransInterval',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transformdevice',
            name='TransPrecision',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transformdevice',
            name='TransPrimary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transformdevice',
            name='TransSecondary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transformdevice',
            name='TransType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
