# Generated by Django 4.2.6 on 2023-12-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0004_alter_transformdevice_trans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpoint',
            name='conclusion_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountpoint',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountpoint',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='conclusion_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='terminate_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='type_agreement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deviceaccount',
            name='model_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objectaccount',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objectaccount',
            name='object_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='inn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='kpp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='mail_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
