# Generated by Django 4.2.6 on 2023-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0008_deviceaccount_meter_interval_deviceaccount_tr_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectaccount',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
