# Generated by Django 4.2.6 on 2023-12-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0010_alter_objectaccount_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id_readings', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Показания',
                'verbose_name_plural': 'Показания',
            },
        ),
        migrations.AlterField(
            model_name='objectaccount',
            name='is_active',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
