# Generated by Django 4.2.6 on 2023-12-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0011_meterreadings_alter_objectaccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceaccount',
            name='DateEnd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
