# Generated by Django 4.2.6 on 2024-01-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0013_agreement_iddogovor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Уведомления',
                'verbose_name_plural': 'Уведомления пользователя',
            },
        ),
    ]
