# Generated by Django 4.2.6 on 2024-01-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0015_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='dateTime',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
