# Generated by Django 4.2.6 on 2024-01-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0016_feedback_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='dateTime',
            new_name='fb_dateTime',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='fb_message',
        ),
    ]
