# Generated by Django 4.2.6 on 2024-01-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0017_rename_datetime_feedback_fb_datetime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
