# Generated by Django 4.2.6 on 2024-01-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fb_email_user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='fb_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='fb_phone_user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='fb_user_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
