# Generated by Django 4.2.6 on 2024-01-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoriz', '0020_feedback_fb_email_user_feedback_fb_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dc_email_admin', models.CharField(max_length=255)),
                ('dc_dateTime', models.CharField(max_length=255)),
                ('dc_username', models.CharField(max_length=255)),
                ('dc_user_agreement', models.CharField(max_length=255)),
                ('dc_filename', models.CharField(max_length=255)),
                ('dc_filepath', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы пользователя',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
